export const GET_DATA_FROM_CSV = 'GET_DATA_FROM_CSV';
export const DATA_FROM_CSV_LOADED = 'DATA_FROM_CSV_LOADED';
export const GET_DATA_FROM_CSV_FAILED = 'GET_DATA_FROM_CSV_FAILED';

export const UPDATE_TABLE_DATA = 'UPDATE_TABLE_DATA';
export const UPDATE_TABLE_TITLE = 'UPDATE_TABLE_TITLE';

export const CHANGE_VIEW_TYPE = 'CHANGE_VIEW_TYPE';